// TRACKS
const audioDirectoryURL = `./music/`;
const coverImagesDirectoryURL = `./images/covers/`;

class MusicTrack {
	constructor(
		id,
		author = 'unnamed',
		title = 'unnamed',
		duration = 0,
		audioURL,
		coverImageURL,
		coverImageSmallURL,
		backgroundColor
	) {
		this.id = id;
		this.author = author;
		this.title = title;
		this.duration = duration;
		this.audioURL = `${audioDirectoryURL}${audioURL}`;
		this.coverImageURL = `${coverImagesDirectoryURL}${coverImageURL}`;
		this.coverImageSmallURL = `${coverImagesDirectoryURL}${coverImageSmallURL}`;
		this.backgroundColor = backgroundColor;
		this.liked = false;
	}
}

const MUSIC = [
	new MusicTrack(
		0,
		'TwinsMusic',
		'No Hip, No Hop',
		118.444458,
		'twinsmusic-nohipnohop.mp3',
		'twinsmusic-nohipnohop.jpg',
		'twinsmusic-nohipnohop_s.jpg',
		'#212626',
	),
	new MusicTrack(
		1,
		'Theatre Of Delays',
		'Last Light',
		310.261589,
		'theatreofdelays-lastlight.mp3',
		'theatreofdelays-lastlight.jpg',
		'theatreofdelays-lastlight_s.jpg',
		'#242B28',
	),
	new MusicTrack(
		2,
		'Roger Gabalda',
		'Curious Child',
		169.957922,
		'rogergabalda-curiouschild.mp3',
		'rogergabalda-curiouschild.jpg',
		'rogergabalda-curiouschild_s.jpg',
		'#2F3029',
	),
	new MusicTrack(
		3,
		'Van Stee',
		'Rebels Of Our Own',
		243.727711,
		'vanstee-rebelsofourownkind.mp3',
		'vanstee-rebelsofourownkind.jpg',
		'vanstee-rebelsofourownkind_s.jpg',
		'#212622',
	),
	new MusicTrack(
		4,
		'Lunar Years',
		'Late Night',
		163.453458,
		'lunaryears-latenight.mp3',
		'lunaryears-latenight.jpg',
		'lunaryears-latenight_s.jpg',
		'#292E30',
	),
	new MusicTrack(
		5,
		'Theatre Of Delays',
		'Prism',
		211.2575,
		'theatreofdelays-prism.mp3',
		'theatreofdelays-prism.jpg',
		'theatreofdelays-prism_s.jpg',
		'#2B2B2B',
	),
	new MusicTrack(
		6,
		'Vic Sage',
		'Grind',
		280.873833,
		'vicsage-grind.mp3',
		'vicsage-grind.jpg',
		'vicsage-grind_s.jpg',
		'#242424',
	),
	new MusicTrack(
		7,
		'Theatre Of Delays',
		'Serpentine',
		198.353044,
		'theatreofdelays-serpentine.mp3',
		'theatreofdelays-serpentine.jpg',
		'theatreofdelays-serpentine_s.jpg',
		'#272524',
	),
	new MusicTrack(
		8,
		'TURNIQUE',
		'Echo Of Sadness',
		139.159544,
		'turnique-echoofsadness.mp3',
		'turnique-echoofsadness.jpg',
		'turnique-echoofsadness_s.jpg',
		'#232621',
	),
	new MusicTrack(
		9,
		'Theatre Of Delays',
		'The Silent Road',
		207.6265,
		'theatreofdelays-thesilentroad.mp3',
		'theatreofdelays-thesilentroad.jpg',
		'theatreofdelays-thesilentroad_s.jpg',
		'#262626',
	),
	new MusicTrack(
		10,
		'Yunior Arronte',
		'Voyage',
		196.263256,
		'yuniorarronte-voyage.mp3',
		'yuniorarronte-voyage.jpg',
		'yuniorarronte-voyage_s.jpg',
		'#2B232A',
	),
	new MusicTrack(
		11,
		'Zam',
		'Lucky',
		159.770167,
		'zam-lucky.mp3',
		'zam-lucky.jpg',
		'zam-lucky_s.jpg',
		'#23272B',
	),
	new MusicTrack(
		12,
		'Hugo Dujardin',
		'Sun',
		198.6665,
		'sun-hugodujardin.mp3',
		'sun-hugodujardin.jpg',
		'sun-hugodujardin_s.jpg',
		'#292E30',
	),
	new MusicTrack(
		13,
		'Kneat',
		'Prostrate',
		148.224044,
		'kneat-prostrate.mp3',
		'kneat-prostrate.jpg',
		'kneat-prostrate_s.jpg',
		'#25232B',
	),
	new MusicTrack(
		14,
		'Diffie Bosman',
		'Black Box',
		207.731,
		'diffiebosman-blackbox.mp3',
		'diffiebosman-blackbox.jpg',
		'diffiebosman-blackbox_s.jpg',
		'#2B2F32',
	),
	new MusicTrack(
		15,
		'Roman Senyk',
		'Remembrance',
		121.944878,
		'romansenyk-remembrance.mp3',
		'romansenyk-remembrance.jpg',
		'romansenyk-remembrance_s.jpg',
		'#2E3029',
	),
	new MusicTrack(
		16,
		'Evert Zeevalkink',
		'Long Road',
		171.493878,
		'evertzeevalkink-longroad.mp3',
		'evertzeevalkink-longroad.jpg',
		'evertzeevalkink-longroad_s.jpg',
		'#2B2A32',
	),
	new MusicTrack(
		17,
		'C.W.',
		'Room Service',
		158.176708,
		'cw-roomservice.mp3',
		'cw-roomservice.jpg',
		'cw-roomservice_s.jpg',
		'#30322B',
	),
	new MusicTrack(
		18,
		'Evert Zeevalkink',
		'On The Roads',
		135.215083,
		'evertzeevalkink-ontheroads.mp3',
		'evertzeevalkink-ontheroads.jpg',
		'evertzeevalkink-ontheroads_s.jpg',
		'#2B2B32',
	),
	new MusicTrack(
		19,
		'Moody Finn',
		'Stylish Car',
		165.459625,
		'moodyfinn-stylishcar.mp3',
		'moodyfinn-stylishcar.jpg',
		'moodyfinn-stylishcar_s.jpg',
		'#302C29',
	),
	new MusicTrack(
		20,
		'Veace D',
		'Closer To The Sun',
		143.386125,
		'veaced-closertothesun.mp3',
		'veaced-closertothesun.jpg',
		'veaced-closertothesun_s.jpg',
		'#212626',
	),
	new MusicTrack(
		21,
		'Marcus P.',
		'Moving Way Up',
		144.065333,
		'marcusp-movingwayup.mp3',
		'marcusp-movingwayup.jpg',
		'marcusp-movingwayup_s.jpg',
		'#2C2A28',
	),
	new MusicTrack(
		22,
		'Neptune',
		'Spotlight',
		128.600833,
		'neptune-spotlight.mp3',
		'neptune-spotlight.jpg',
		'neptune-spotlight_s.jpg',
		'#302F29',
	),
	new MusicTrack(
		23,
		'Benjamin Lazzarus',
		'Les Prisonnieres',
		249.344044,
		'benjaminlazzarus-lesprisonnieres.mp3',
		'benjaminlazzarus-lesprisonnieres.jpg',
		'benjaminlazzarus-lesprisonnieres_s.jpg',
		'#313131',
	),
	new MusicTrack(
		24,
		'Elliot',
		'Bass Buzzer',
		85.577167,
		'elliot-bassbuzzer.mp3',
		'elliot-bassbuzzer.jpg',
		'elliot-bassbuzzer_s.jpg',
		'#3C3B38',
	),
	new MusicTrack(
		25,
		'Sonobringer',
		'Stellar Catharsis',
		195.322833,
		'sonobringer-stellarcatharsis.mp3',
		'sonobringer-stellarcatharsis.jpg',
		'sonobringer-stellarcatharsis_s.jpg',
		'#111B2B',
	),
	new MusicTrack(
		26,
		'Vic Sage',
		'No Hook',
		135.341333,
		'vicsage-nohook.mp3',
		'vicsage-nohook.jpg',
		'vicsage-nohook_s.jpg',
		'#2B2923',
	),
	new MusicTrack(
		27,
		'Vic Sage',
		'Twenty-five',
		112.749756,
		'vicsage-twentyfive.mp3',
		'vicsage-twentyfive.jpg',
		'vicsage-twentyfive_s.jpg',
		'#242424',
	),
	new MusicTrack(
		28,
		'Yari',
		'Fly Forward',
		109.667333,
		'yari-flyforward.mp3',
		'yari-flyforward.jpg',
		'yari-flyforward_s.jpg',
		'#2B2623',
	),
	new MusicTrack(
		29,
		'Vital',
		'Lifestyle Thing',
		120.116292,
		'vital-lifestylething.mp3',
		'vital-lifestylething.jpg',
		'vital-lifestylething_s.jpg',
		'#23242B',
	),
	new MusicTrack(
		30,
		'Soyb',
		'Night and Day',
		145.371458,
		'soyb-nightandday.mp3',
		'soyb-nightandday.jpg',
		'soyb-nightandday_s.jpg',
		'#30292B',
	),
	new MusicTrack(
		31,
		'PillowVibes',
		'Sport Car Beat',
		119.771375,
		'pillowvibes-sportcarbeat.mp3',
		'pillowvibes-sportcarbeat.jpg',
		'pillowvibes-sportcarbeat_s.jpg',
		'#302C29',
	),
	new MusicTrack(
		32,
		'Pure',
		'Sunny District',
		117.629375,
		'pure-sunnydistrict.mp3',
		'pure-sunnydistrict.jpg',
		'pure-sunnydistrict_s.jpg',
		'#302929',
	),
	new MusicTrack(
		33,
		'AHOAMI',
		'Demon',
		149.368125,
		'ahoami-demon.mp3',
		'ahoami-demon.jpg',
		'ahoami-demon_s.jpg',
		'#322D2B',
	),
	new MusicTrack(
		34,
		'SHANTI',
		'Vlog Vibe',
		117.49875,
		'shanti-vlogvibe.mp3',
		'shanti-vlogvibe.jpg',
		'shanti-vlogvibe_s.jpg',
		'#302A29',
	),
	new MusicTrack(
		35,
		'Alexey Anisimov',
		'Travel Vlog',
		107.546063,
		'alexeyanisimov-travelvlog.mp3',
		'alexeyanisimov-travelvlog.jpg',
		'alexeyanisimov-travelvlog_s.jpg',
		'#2B3230',
	),
	new MusicTrack(
		36,
		'ROADTOMUSIC',
		'Bounce',
		110.158313,
		'roadtomusic-bounce.mp3',
		'roadtomusic-bounce.jpg',
		'roadtomusic-bounce_s.jpg',
		'#302E29',
	),
	new MusicTrack(
		37,
		'RomaYoung',
		'Funky Hip-Hop',
		177.92,
		'romayoung-funkyhiphop.mp3',
		'romayoung-funkyhiphop.jpg',
		'romayoung-funkyhiphop_s.jpg',
		'#302929',
	),
	new MusicTrack(
		38,
		'CloudSystem',
		'Yayo',
		80.848938,
		'cloudsystem-yayo.mp3',
		'cloudsystem-yayo.jpg',
		'cloudsystem-yayo_s.jpg',
		'#27212E',
	),
	new MusicTrack(
		39,
		'Musical Bakery',
		'Funky Dope',
		128.078313,
		'musicalbakery-funkydope.mp3',
		'musicalbakery-funkydope.jpg',
		'musicalbakery-funkydope_s.jpg',
		'#302930',
	),
	new MusicTrack(
		40,
		'Theatre Of Delays',
		'Corrupted Reality',
		258.199544,
		'theatreofdelays-corruptedreality.mp3',
		'theatreofdelays-corruptedreality.jpg',
		'theatreofdelays-corruptedreality_s.jpg',
		'#2B2B2B',
	),
	new MusicTrack(
		41,
		'Joshua Naranjo',
		'Solitude',
		251.042,
		'joshuanaranjo-solitude.mp3',
		'joshuanaranjo-solitude.jpg',
		'joshuanaranjo-solitude_s.jpg',
		'#2B2A23',
	),
	new MusicTrack(
		42,
		'Diffie Bosman',
		'Nova Scotia',
		325.856711,
		'diffiebosman-novascotia.mp3',
		'diffiebosman-novascotia.jpg',
		'diffiebosman-novascotia_s.jpg',
		'#252E2F',
	),
	new MusicTrack(
		43,
		'FoePound',
		'Vanishing Hope',
		129.311422,
		'foepound-vanishinghope.mp3',
		'foepound-vanishinghope.jpg',
		'foepound-vanishinghope_s.jpg',
		'#2C2E31',
	),
	new MusicTrack(
		44,
		'FoePound',
		'Please Keep Quiet',
		138.428125,
		'foepound-pleasekeepquiet.mp3',
		'foepound-pleasekeepquiet.jpg',
		'foepound-pleasekeepquiet_s.jpg',
		'#2B2E32',
	),
	new MusicTrack(
		45,
		'Theatre Of Delays',
		'Trace',
		322.121211,
		'theatreofdelays-trace.mp3',
		'theatreofdelays-trace.jpg',
		'theatreofdelays-trace_s.jpg',
		'#252626',
	),
	new MusicTrack(
		46,
		'DPMusic',
		'Boundless Space',
		125.152667,
		'dpmusic-boundlessspace.mp3',
		'dpmusic-boundlessspace.jpg',
		'dpmusic-boundlessspace_s.jpg',
		'#383835',
	),
	new MusicTrack(
		47,
		'Theatre Of Delays',
		'Exile',
		207.4645,
		'theatreofdelays-exile.mp3',
		'theatreofdelays-exile.jpg',
		'theatreofdelays-exile_s.jpg',
		'#2B2B2B',
	),
	new MusicTrack(
		48,
		'VictorWayne',
		'Walk',
		125.38775,
		'victorwayne-walk.mp3',
		'victorwayne-walk.jpg',
		'victorwayne-walk_s.jpg',
		'#2B2623',
	),
	new MusicTrack(
		49,
		'Rage Sound',
		'End of Everything',
		132.048938,
		'ragesound-endofeverything.mp3',
		'ragesound-endofeverything.jpg',
		'ragesound-endofeverything_s.jpg',
		'#292F30',
	),
	new MusicTrack(
		50,
		'VictorWayne',
		'Time',
		132.048938,
		'victorwayne-time.mp3',
		'victorwayne-time.jpg',
		'victorwayne-time_s.jpg',
		'#23252B',
	),
	new MusicTrack(
		51,
		'SoundMolecule',
		'Smoke on the road',
		89.704438,
		'soundmolecule-smokeontheroad.mp3',
		'soundmolecule-smokeontheroad.jpg',
		'soundmolecule-smokeontheroad_s.jpg',
		'#292C30',
	),
	new MusicTrack(
		52,
		'SoundMolecule',
		'Make A Comeback',
		91.924875,
		'soundmolecule-makeacomeback.mp3',
		'soundmolecule-makeacomeback.jpg',
		'soundmolecule-makeacomeback_s.jpg',
		'#2D2A29',
	),
	new MusicTrack(
		53,
		'RocknStock',
		'Energy Sport',
		120.398313,
		'rocknstock-energysport.mp3',
		'rocknstock-energysport.jpg',
		'rocknstock-energysport_s.jpg',
		'#2C2222',
	),
	new MusicTrack(
		54,
		'RocknStock',
		'Rock It',
		172.721625,
		'rocknstock-rockit.mp3',
		'rocknstock-rockit.jpg',
		'rocknstock-rockit_s.jpg',
		'#292E30',
	),
	new MusicTrack(
		55,
		'AlexGuz',
		'Classic Rock Vibe',
		137.377938,
		'alexguz-classicrockvibe.mp3',
		'alexguz-classicrockvibe.jpg',
		'alexguz-classicrockvibe_s.jpg',
		'#363636'
	),
	new MusicTrack(
		56,
		'Romanov_Studio',
		'Rock Crowd',
		120.032625,
		'romanovstudio-rockcrowd.mp3',
		'romanovstudio-rockcrowd.jpg',
		'romanovstudio-rockcrowd_s.jpg',
		'#302D29',
	),
	new MusicTrack(
		57,
		'AndyWarner',
		'Perfect Day',
		413.38775,
		'andywarner-perfectday.mp3',
		'andywarner-perfectday.jpg',
		'andywarner-perfectday_s.jpg',
		'#273330',
	),
	new MusicTrack(
		58,
		'Rage Sound',
		'Cool Team',
		122.070188,
		'ragesound-coolteam.mp3',
		'ragesound-coolteam.jpg',
		'ragesound-coolteam_s.jpg',
		'#302C29',
	),
	new MusicTrack(
		59,
		'EdRecords',
		'Bull Horns',
		104.939167,
		'edrecords-bullhorns.mp3',
		'edrecords-bullhorns.jpg',
		'edrecords-bullhorns_s.jpg',
		'#2B322C',
	),
	new MusicTrack(
		60,
		'EdRecords',
		'Fast And Wild',
		97.624875,
		'edrecords-fastandwild.mp3',
		'edrecords-fastandwild.jpg',
		'edrecords-fastandwild_s.jpg',
		'#322F2B',
	),
	new MusicTrack(
		61,
		'EdRecords',
		'Rock And Dust',
		93.4975,
		'edrecords-rockanddust.mp3',
		'edrecords-rockanddust.jpg',
		'edrecords-rockanddust_s.jpg',
		'#32322B',
	),
	new MusicTrack(
		62,
		'Ge Filter Fish',
		'Fist Up In The Air',
		180.459167,
		'gefilterfish-fistupintheair.mp3',
		'gefilterfish-fistupintheair.jpg',
		'gefilterfish-fistupintheair_s.jpg',
		'#232B29',
	),
];



// PLAYLISTS
class MusicPlaylist {
	constructor(name, trackIdList) {
		this.name = name;
		this.trackIdList = trackIdList;
	}

	get length() {
		return this.trackIdList.length;
	}
}

const PLAYLISTS = [
	new MusicPlaylist(
		'Favorites',
		[],
	),
	new MusicPlaylist(
		'Popular',
		[28, 3, 34, 24, 0, 1, 19, 32, 45, 46, 26, 44, 6, 35, 61, 36, 62, 52, 27, 12],
	),
	new MusicPlaylist(
		'New',
		[8, 10, 17, 20, 21, 22, 23, 16, 19, 57, 62, 36, 1, 5, 41, 50, 28, 38, 54],
	),
	new MusicPlaylist(
		'Indie',
		[1, 2, 3, 4, 8, 10, 11, 12, 14, 15, 16, 18, 19, 24],
	),
	new MusicPlaylist(
		'Ambient',
		[45, 7, 5, 9, 13, 25, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 1],
	),
	new MusicPlaylist(
		'Hip Hop',
		[0, 6, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
	),
	new MusicPlaylist(
		'Rock',
		[3, 51, 52, 53, 54, 55, 56, 61, 58, 59, 60, 57, 62],
	),
];



export { MUSIC, PLAYLISTS };